kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: mysql
    db: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql
      deployment: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        db: mysql
        deployment: mysql
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: testdb
            - name: MYSQL_PASSWORD
              value: pass
            - name: MYSQL_USER
              value: user
          ports:
            - containerPort: 3306
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/mysql@sha256:9430212003d97d3a0e3584c8dec91e09d1edb36cc2cbf857014fa43a9dbd4ec3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsGroup: 1000650000
        fsGroup: 1000650000
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600